export const FULLFILLMENT_ENUM = {
  FULLFILLMENT_PENDING: "FULLFILLMENT_PENDING",
  FULLFILLMENT_STARTED: "FULLFILLMENT_STARTED",
  FULLFILLMENT_COMPLETED: "FULLFILLMENT_COMPLETED",
  FULLFILLMENT_CANCELLED: "FULLFILLMENT_CANCELLED",
};
